sql: true # Set SQL as main secret storage, if this is set to false, mongodb uri is required
console: true # Console logging
debug: true # Debug enables PProf
locale: en # GoHack Server validation locale

database:
  host: localhost
  user: gohack
  password: gohack
  dbname: gohack
  port: 5432
  timezone: UTC
  sslmode: false
logging:
  level: info # supported logging - debug, info, warning, error

http:
  prefork: false
  address: :4000 # HTTP Address
