sql: true # Set SQL as main secret storage, if this is set to false, mongodb uri is required
debug: true # Debug enables PProf
locale: en # GoHack Server validation locale

database:
  host: postgres
  user: gohack
  password: gohack
  dbname: gohack
  port: 5432
  timezone: UTC
  sslmode: false

# supported logging - debug, info, warning, error
logging:
  level: info # Logger instance used in API
  console: true # Console logging

http:
  prefork: false
  address: :4000 # HTTP Address
