version: '3'

tasks:
  build:
    cmds:
      - go build -o ./build/app{{exeExt}} ./cli/server
  build-prod:
    vars:
    env:
      CGO_ENABLED: 0
      GOOS: linux
      GOARCH: amd64
    cmds:
      - go mod download -x
      - mkdir -p build
      - go build -ldflags="-s -w" -a -installsuffix cgo -o ./build/app{{exeExt}} ./cli/server
  copy-config:
    vars:
      CONFIG_PATH: ./cli/server
      CONFIG_NAME: config.yml
    preconditions:
      - sh: '[ ! -f "{{.CONFIG_PATH}}/{{.CONFIG_NAME}}" ]'
      - msg: 'No config.yml file.'
    cmds:
      - cp ./cli/server/config.example.yml ./cli/server/config.yml
  dev:
    dir: ./cli/server
    cmds:
      - fiber dev --root ../../
  dev-docker:
    cmds:
      - docker run -it --rm -w "/go/src/github.com/BrosSquad/gohack"
    deps:
      - copy-config
