version: '3'

env:
  CGO_ENABLED: 0
  GOOS: {{OS}}
  GOARCH: amd64
tasks:
  build:
    cmd:
      - go build -o ./build/app{{exeExt}} ./cli/server
  build-prod:
    cmd:
      - go mod download -x
      - mkdir -p build
      - go build -a -installsuffix cgo -o ./build/app{{exeExt}} ./cli/server
  copy-config:
    vars:
      CONFIG_PATH: ./cli/server
      CONFIG_NAME: config.yml
    preconditions:
      - sh: '[ ! -f "{{.CONFIG_PATH}}/{{.CONFIG_NAME}}" ]'
      - msg: 'No config.yml file.'
    cmd: cp ./cli/server/config.example.yml ./cli/server/config.yml
  install-go-air:
    preconditions:
      - sh: '[ ! -f "./bin/air" ]'
      - msg: 'No config.yml file.'
    cmd:
      - curl -sSfL https://raw.githubusercontent.com/cosmtrek/air/master/install.sh | sh -s
  dev:
    dir: ./cli/server
    cmd:
      - ./bin/air
    deps:
      - copy-config
      - install-go-air
  dev-docker:
    env:
      GOPATH: /go
    cmd:
      - docker run -it --rm -w "/go/src/github.com/BrosSquad/gohack" \
        -v $(pwd):/go/src/github.com/BrosSquad/gohack -p 4000:4000 cosmtrek/air
    deps:
      - copy-config